local_manifest: Drop unused repos
* android_hardware_xiaomi is unused for our device and will throw a dependency error when its not removed

error: hardware/xiaomi/vibrator/effect/Android.bp:4:1: dependency "libc++fs" of "libqtivibratoreffect.xiaomi" missing variant:

Signed-off-by: Christopher <mizdrake7@gmail.com>